enum ActionTypeKeys {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  ADD_TODO = 'ADD_TODO',
  EDIT_TODO = 'EDIT_TODO',
  MARK_TODO_COMPLETE = 'MARK_TODO_COMPLETE',
  MARK_TODO_INCOMPLETE = 'MARK_TODO_INCOMPLETE',
  DELETE_TODO = 'DELETE_TODO',
  CHANGE_FILTER = 'CHANGE_FILTER',
}

export default ActionTypeKeys;
